---
apiVersion: awx.ansible.com/v1beta1
kind: AWX

metadata:
  name: awx
  namespace: awx

spec:
  service_type: LoadBalancer
  loadbalancer_source_ranges:
    - 165.225.93.53/32  # Your laptop IP addr

  postgres_configuration_secret: awx-postgres-configuration

  projects_persistence: true
  projects_storage_class: azurefile-csi
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 5Gi

  web_resource_requirements:
    requests:
      cpu: 250m
      memory: 512Mi

  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 512Mi

  ingress_type: none
